# Travis CI (MIT License) configuration file for the ACF Content Blocks WP plugin
# @link https://travis-ci.org/

# Declare project language.
# @link http://about.travis-ci.org/docs/user/languages/php/
language: php

# Declare versions of PHP to use. Use one decimal max.
php:
  # aliased to a recent 5.6.x version
  - "5.6"
  # aliased to a recent 5.5.x version
  - "5.5"

# Use this to prepare the system to install prerequisites or dependencies.
# e.g. sudo apt-get update.
# Failures in this section will result in build status 'errored'.
# before_install:

# Use this to prepare your build for testing.
# e.g. copy database configurations, environment variables, etc.
# Failures in this section will result in build status 'errored'.
before_script:
  - export PLUGIN_DEV_DIR=/tmp/dev/
  - mkdir -p $PLUGIN_DEV_DIR
  - plugin_slug=$(basename $(pwd))
  - plugin_dir=$PLUGIN_DEV_DIR/$plugin_slug
  - cd ..
  - mv $plugin_slug $plugin_dir
  - cd $PLUGIN_DEV_DIR
  # Install CodeSniffer for WordPress Coding Standards checks.
  - git clone https://github.com/squizlabs/PHP_CodeSniffer.git php-codesniffer
  # Install WordPress Coding Standards.
  - git clone https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git wordpress-coding-standards
  # Hop into CodeSniffer directory.
  - cd php-codesniffer
  # Set install path for WordPress Coding Standards
  # @link https://github.com/squizlabs/PHP_CodeSniffer/blob/4237c2fc98cc838730b76ee9cee316f99286a2a7/CodeSniffer.php#L1941
  - bin/phpcs --config-set installed_paths ../wordpress-coding-standards
  # Hop into plugins directory.
  - cd $plugin_dir
  # After CodeSniffer install you should refresh your path.
  - phpenv rehash

# Run test script commands.
# Default is specific to project language.
# All commands must exit with code 0 on success. Anything else is considered failure.
script:
  # Search for PHP syntax errors.
  - find . \( -name '*.php' \) | xargs -I file php -lf file
  # WordPress Coding Standards
  # @link https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards
  # @link http://pear.php.net/package/PHP_CodeSniffer/
  # -p flag: Show progress of the run.
  # -s flag: Show sniff codes in all reports.
  # -v flag: Print verbose output.
  # -n flag: Do not print warnings (shortcut for --warning-severity=0)
  # --standard: Use WordPress as the standard.
  # --extensions: Only sniff PHP files.
  - $PLUGIN_DEV_DIR/php-codesniffer/bin/phpcs -p -s -v -n . --standard=WordPress --extensions=php

# Receive notifications for build results.
# @link http://docs.travis-ci.com/user/notifications/#Email-notifications
notifications:
  email: true